/**
 * Below are the constants for modeling the Tetris game state.
 */

// The standard Tetris game board is 20x10 (20 rows, length 10 rows.)
export const GAME_BOARD_NUM_ROWS = 20;
export const GAME_BOARD_ROW_LENGTH = 10;

/** There are 7 set pieces that can be randomly generated by the game, and they are named
 *  'O', 'I', 'S', 'Z', 'L', 'J', and 'T'.
 *
 *  A 1 denotes the actual "block" of the piece, while a 0 denotes
 *  the game square is empty (still a "part" of the piece).
 * */

export const O_PIECE = [
  [1, 1],
  [1, 1],
];
export const I_PIECE = [[1], [1], [1], [1]];
export const S_PIECE = [
  [0, 1, 1],
  [1, 1, 0],
];
export const Z_PIECE = [
  [1, 1, 0],
  [0, 1, 1],
];
export const L_PIECE = [
  [1, 0],
  [1, 0],
  [1, 1],
];
export const J_PIECE = [
  [0, 1],
  [0, 1],
  [1, 1],
];
export const T_PIECE = [
  [1, 1, 1],
  [0, 1, 0],
];
